<?php
	
	// Append new icons
    $custom_icons = array(
        'angle-up',
        'check',
        'calendar',
        'language',
        'shopping-cart',
        'bars',
        'search',
        // 'map-marker',
        // 'arrow-right',
        // 'arrow-left',
        // 'arrow-up',
        // 'arrow-down',
        // 'angle-right',
        // 'angle-left',
        // 'angle-up',
        // 'angle-down',
        // 'phone',
        // 'users',
        // 'user',
        // 'map-marked-alt',
        // 'trophy-alt',
        // 'envelope',
        // 'marker',
        // 'globe',
        // 'broom',
        // 'home',
        // 'bed',
        // 'chair',
        // 'bath',
        // 'tree',
        // 'laptop-code',
        // 'cube',
        // 'cog',
        // 'play',
        // 'trophy-alt',
        // 'heart',
        // 'truck',
        // 'user-circle',
        // 'map-marker-alt',
        // 'comments',
        // 'award',
        // 'bell',
        // 'book-alt',
        // 'book-open',
        // 'book-reader',
        // 'graduation-cap',
        // 'laptop-code',
        // 'music',
        // 'ruler-triangle',
        // 'user-graduate',
        // 'microscope',
        // 'glasses-alt',
        // 'theater-masks',
        // 'atom'
    );    


        